# Generated by Django 2.2.16 on 2022-11-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(default=None, max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
